version: '3.6'

networks:
  default:
    external:
      name: iict-chain-member_default

services:

  blockscout:
    image: consensys/blockscout:v4.0.0-beta
    container_name: blockscout
    restart: "no"
    environment:
      - PORT=4000
      - DATABASE_URL=ecto://postgres:postgres@postgres/postgres?ssl=false
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - NETWORK=中科乐联
      - SUBNETWORK=雨海纪
      - CHAIN_ID=1337
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=besu
      - ETHEREUM_JSONRPC_TRANSPORT=http
      - ETHEREUM_JSONRPC_HTTP_URL=http://member.iict.cas-ll.net:8545
      - ETHEREUM_JSONRPC_TRACE_URL=http://member.iict.cas-ll.net:8545
      - ETHEREUM_JSONRPC_WS_URL=ws://member.iict.cas-ll.net:8546
      - DISABLE_EXCHANGE_RATES=true
      - DISABLE_KNOWN_TOKENS=true
      - ENABLE_TXS_STATS=true
      - SHOW_PRICE_CHART=false
      - SHOW_TXS_CHART=true
      - LINK_TO_OTHER_EXPLORERS=false
      - OTHER_EXPLORERS=[]
      - SUPPORTED_CHAINS=[]
      - BLOCKSCOUT_VERSION=4.0.0
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /opt/app/;
        echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - 8080:4000
    volumes:
      - ./blockscout/_topnav.html.eex:/opt/app/apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
      - ./blockscout/_footer.html.eex:/opt/app/apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    restart: "on-failure"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 5
