version: '3.6'

networks:
  explorer:
    external:
      name: iict-chain-member_default

services:
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    restart: "on-failure"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - explorer
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      retries: 5
  
  blockscout:
    image: consensys/blockscout:v4.0.0-beta
    container_name: blockscout
    restart: "no"
    environment:
      - PORT=4000
      - DATABASE_URL=ecto://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/postgres?ssl=false
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - NETWORK=中科乐联
      - SUBNETWORK=雨海纪
      - CHAIN_ID=1337
      - COIN=ETH
      - ETHEREUM_JSONRPC_VARIANT=besu
      - ETHEREUM_JSONRPC_TRANSPORT=http
      - ETHEREUM_JSONRPC_HTTP_URL=${ETHEREUM_JSONRPC_HTTP_URL}
      - ETHEREUM_JSONRPC_TRACE_URL=${ETHEREUM_JSONRPC_HTTP_URL}
      - ETHEREUM_JSONRPC_WS_URL=${ETHEREUM_JSONRPC_WS_URL}
      - DISABLE_EXCHANGE_RATES=true
      - DISABLE_KNOWN_TOKENS=true
      - ENABLE_TXS_STATS=true
      - SHOW_PRICE_CHART=false
      - SHOW_TXS_CHART=true
      - LINK_TO_OTHER_EXPLORERS=false
      - OTHER_EXPLORERS=[]
      - SUPPORTED_CHAINS=[]
      - BLOCKSCOUT_VERSION=4.0.0
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /opt/app/;
        echo $$MIX_ENV && mix do ecto.create, ecto.migrate; mix phx.server;
    depends_on:
      - postgres
    ports:
      - 4000:4000
    volumes:
      - ./blockscout/_topnav.html.eex:/opt/app/apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
      - ./blockscout/_footer.html.eex:/opt/app/apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
    networks:
      - explorer
    healthcheck:
      test: [ "CMD-SHELL", "curl http://blockscout:4000 || exit 1" ]
      retries: 5